sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UwoGAPVT7cg5lmq6f4d2OIU8Aeoow7fDUFz5972X78qDb2EdcVGNP2RQohlmlwtGE2MVD4ZqFHIqVwGNFOzHOzyjsJ4hyFYB1X4wyocALWvKetLPZEvnXXSqpAVuftWd1SNaWb1/EqT9laf/JbVHPpUNqP3bO4r8Es09DVYe4thcS3t8H+/da5W5xlW2Toc+bxGx9FZhnP7t4JT8LVCkgsLer+SdjdNbapmkRzL/7Y+j25j3GbPePgbFfiXbkrd6fLOWxNReoPHI7tPpmktIntFdtdN3IcwvhJ3r5KrpwLqXfRzqnvcN/rMVVSUHejoYeLmKv1WhXAJo4u70L7EvE3GuLe9NSoN6X15Cbzej9WjVHCxs9tJynZfuruYvn2ptFif1Z/e+IGZ955YMeUT8eTjqM5UnJri1CEMLxpu2Tu/OvG90QE3tCkD6bolwNWWikzCMDWJyRzgSGM55EZYQ7G8pGenwVEoqJBAWVY9hcOlIkatEJAVIJ4xxT2PnSk2bBf6ujBu3YAF0Rzf2loQrXwpXnNweVQC4jUSucTQ2zS/wJmcmqlXsL9S59Bjznf+CYPzatx6Gm/QzuVi/jwwqcJE4PcGgVqaCidTtZgrTq6e0I8wD06PzKDBN9sK16iwjyFK4m8lK0gp73Zw227X9eV8t0rODSxGFziVz3U/W99U=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Story-of-the-Gadsbys_2821
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy